make clean TEST_SRC=libflame_potrf; make TEST_SRC=libflame_potrf;
make clean TEST_SRC=libflame_potf2; make TEST_SRC=libflame_potf2;
make clean TEST_SRC=libflame_getrf; make TEST_SRC=libflame_getrf;
make clean TEST_SRC=libflame_getf2; make TEST_SRC=libflame_getf2;
make clean TEST_SRC=libflame_geqrf; make TEST_SRC=libflame_geqrf;
make clean TEST_SRC=libflame_geqr2; make TEST_SRC=libflame_geqr2;
make clean TEST_SRC=libflame_geqpf; make TEST_SRC=libflame_geqpf;
make clean TEST_SRC=libflame_geqp3; make TEST_SRC=libflame_geqp3;
make clean TEST_SRC=libflame_gelqf; make TEST_SRC=libflame_gelqf;
make clean TEST_SRC=libflame_gelq2; make TEST_SRC=libflame_gelq2;
make clean TEST_SRC=libflame_gelsd; make TEST_SRC=libflame_gelsd;
make clean TEST_SRC=libflame_gelss; make TEST_SRC=libflame_gelss;
make clean TEST_SRC=libflame_lauum; make TEST_SRC=libflame_lauum;
make clean TEST_SRC=libflame_lauu2; make TEST_SRC=libflame_lauu2;
make clean TEST_SRC=libflame_potri; make TEST_SRC=libflame_potri;
make clean TEST_SRC=libflame_trtri; make TEST_SRC=libflame_trtri;
make clean TEST_SRC=libflame_trti2; make TEST_SRC=libflame_trti2;
make clean TEST_SRC=libflame_trsyl; make TEST_SRC=libflame_trsyl;
make clean TEST_SRC=libflame_gehrd; make TEST_SRC=libflame_gehrd;
make clean TEST_SRC=libflame_gehd2; make TEST_SRC=libflame_gehd2;
make clean TEST_SRC=libflame_sytrd; make TEST_SRC=libflame_sytrd;
make clean TEST_SRC=libflame_hetrd; make TEST_SRC=libflame_hetrd;
make clean TEST_SRC=libflame_sytd2; make TEST_SRC=libflame_sytd2;
make clean TEST_SRC=libflame_hetd2; make TEST_SRC=libflame_hetd2;
make clean TEST_SRC=libflame_gebrd; make TEST_SRC=libflame_gebrd;
make clean TEST_SRC=libflame_gebd2; make TEST_SRC=libflame_gebd2;
make clean TEST_SRC=libflame_sygst; make TEST_SRC=libflame_sygst;
make clean TEST_SRC=libflame_hegst; make TEST_SRC=libflame_hegst;
make clean TEST_SRC=libflame_sygs2; make TEST_SRC=libflame_sygs2;
make clean TEST_SRC=libflame_hegs2; make TEST_SRC=libflame_hegs2;
make clean TEST_SRC=libflame_larft; make TEST_SRC=libflame_larft;
make clean TEST_SRC=libflame_larfg; make TEST_SRC=libflame_larfgp;
make clean TEST_SRC=libflame_larfg; make TEST_SRC=libflame_larfg;
make clean TEST_SRC=libflame_orgqr; make TEST_SRC=libflame_orgqr;
make clean TEST_SRC=libflame_ungqr; make TEST_SRC=libflame_ungqr;
make clean TEST_SRC=libflame_ormqr; make TEST_SRC=libflame_ormqr;
make clean TEST_SRC=libflame_unmqr; make TEST_SRC=libflame_unmqr;
make clean TEST_SRC=libflame_orm2r; make TEST_SRC=libflame_orm2r;
make clean TEST_SRC=libflame_unm2r; make TEST_SRC=libflame_unm2r;
make clean TEST_SRC=libflame_orglq; make TEST_SRC=libflame_orglq;
make clean TEST_SRC=libflame_unglq; make TEST_SRC=libflame_unglq;
make clean TEST_SRC=libflame_ormlq; make TEST_SRC=libflame_ormlq;
make clean TEST_SRC=libflame_unmlq; make TEST_SRC=libflame_unmlq;
make clean TEST_SRC=libflame_orml2; make TEST_SRC=libflame_orml2;
make clean TEST_SRC=libflame_unml2; make TEST_SRC=libflame_unml2;
make clean TEST_SRC=libflame_orgtr; make TEST_SRC=libflame_orgtr;
make clean TEST_SRC=libflame_ungtr; make TEST_SRC=libflame_ungtr;
make clean TEST_SRC=libflame_ormtr; make TEST_SRC=libflame_ormtr;
make clean TEST_SRC=libflame_unmtr; make TEST_SRC=libflame_unmtr;
make clean TEST_SRC=libflame_orgbr; make TEST_SRC=libflame_orgbr;
make clean TEST_SRC=libflame_ungbr; make TEST_SRC=libflame_ungbr;
make clean TEST_SRC=libflame_ormbr; make TEST_SRC=libflame_ormbr;
make clean TEST_SRC=libflame_unmbr; make TEST_SRC=libflame_unmbr;
make clean TEST_SRC=libflame_steqr; make TEST_SRC=libflame_steqr;
make clean TEST_SRC=libflame_stedc; make TEST_SRC=libflame_stedc;
make clean TEST_SRC=libflame_stemr; make TEST_SRC=libflame_stemr;
make clean TEST_SRC=libflame_syev ; make TEST_SRC=libflame_syev ;
make clean TEST_SRC=libflame_heev ; make TEST_SRC=libflame_heev ;
make clean TEST_SRC=libflame_syevd; make TEST_SRC=libflame_syevd;
make clean TEST_SRC=libflame_heevd; make TEST_SRC=libflame_heevd;
make clean TEST_SRC=libflame_syevr; make TEST_SRC=libflame_syevr;
make clean TEST_SRC=libflame_heevr; make TEST_SRC=libflame_heevr;
make clean TEST_SRC=libflame_bdsqr; make TEST_SRC=libflame_bdsqr;
make clean TEST_SRC=libflame_bdsdc; make TEST_SRC=libflame_bdsdc;
make clean TEST_SRC=libflame_gesvd; make TEST_SRC=libflame_gesvd;
make clean TEST_SRC=libflame_gesdd; make TEST_SRC=libflame_gesdd;
make clean TEST_SRC=libflame_laswp; make TEST_SRC=libflame_laswp;
make clean TEST_SRC=libflame_laset; make TEST_SRC=libflame_laset;
./libflame_potrf;
./libflame_potf2;
./libflame_getrf;
./libflame_getf2;
./libflame_geqrf;
./libflame_geqr2;
./libflame_geqpf;
./libflame_geqp3;
./libflame_gelqf;
./libflame_gelq2;
./libflame_gelsd;
./libflame_gelss;
./libflame_lauum;
./libflame_lauu2;
./libflame_potri;
./libflame_trtri;
./libflame_trti2;
./libflame_trsyl;
./libflame_gehrd;
./libflame_gehd2;
./libflame_sytrd;
./libflame_hetrd;
./libflame_sytd2;
./libflame_hetd2;
./libflame_gebrd;
./libflame_gebd2;
./libflame_sygst;
./libflame_hegst;
./libflame_sygs2;
./libflame_hegs2;
./libflame_larft;
./libflame_larfgp;
./libflame_larfg;
./libflame_orgqr;
./libflame_ungqr;
./libflame_ormqr;
./libflame_unmqr;
./libflame_orm2r;
./libflame_unm2r;
./libflame_orglq;
./libflame_unglq;
./libflame_ormlq;
./libflame_unmlq;
./libflame_orml2;
./libflame_unml2;
./libflame_orgtr;
./libflame_ungtr;
./libflame_ormtr;
./libflame_unmtr;
./libflame_orgbr;
./libflame_ungbr;
./libflame_ormbr;
./libflame_unmbr;
./libflame_steqr;
./libflame_stedc;
./libflame_stemr;
./libflame_syev ;
./libflame_heev ;
./libflame_syevd;
./libflame_heevd;
./libflame_syevr;
./libflame_heevr;
./libflame_bdsqr;
./libflame_bdsdc;
./libflame_gesvd;
./libflame_gesdd;
./libflame_laswp;
./libflame_laset;
