#!/bin/bash

LIBAOCLUTILS_DIR=libaoclutils
LIBAOCLUTILS_OBJ_DIR=libaoclutils_objdir
LIBAOCLUTILS_STATICLIB=libaoclutils.a
LIBAOCLUTILS_GIT_URL=git@github.amd.com:AOCL/aocl-utils.git
LIBAOCLUTILS_GIT_TAG=amd-main
LIBAOCLUTILS_GIT_REPO=aocl-utils

rm -r $LIBAOCLUTILS_DIR
mkdir -p $LIBAOCLUTILS_DIR
rm -r $LIBAOCLUTILS_OBJ_DIR 
mkdir -p $LIBAOCLUTILS_OBJ_DIR
cd $LIBAOCLUTILS_DIR
git clone $LIBAOCLUTILS_GIT_URL -b $LIBAOCLUTILS_GIT_TAG
cd $LIBAOCLUTILS_GIT_REPO
mkdir build_temp
cd build_temp
cmake ..
make -j
cp $LIBAOCLUTILS_STATICLIB ../../../$LIBAOCLUTILS_OBJ_DIR
cd ../../../$LIBAOCLUTILS_OBJ_DIR
ar -x $LIBAOCLUTILS_STATICLIB
cd ..
