GBENCH_SRC_FILE_LIST = EIG/Flame_gbench_hseqr.o \
EIG/Flame_gbench_geevx.o \
EIG/Flame_gbench_heevd.o \
LIN/Flame_gbench_getrs.o \
EIG/Flame_gbench_geev.o \
LIN/Flame_gbench_pocon.o \
LIN/Flame_gbench_gecon.o \
EIG/Flame_gbench_orghr.o \
EIG/Flame_gbench_gehrd.o \
LIN/Flame_gbench_geqr.o \
LIN/Flame_gbench_geqrf.o \
LIN/Flame_gbench_geqr.o \
EIG/Flame_gbench_ggev.o \
EIG/Flame_gbench_syevd.o \
LIN/Flame_gbench_getrf.o \
LIN/Flame_gbench_potrf.o \
SVD/Flame_gbench_gesvd.o
